# /etc/rc.conf -- SzpontOS System Configuration
# (C) Copyright by Szpont Industries. Inspired by FreeBSD rc.conf.

# Host & System Identity
hostname="szpontos"

# Network Configuration (Intel E1000 / em0)
network_enable="YES"
ifconfig_em0="10.0.2.15 netmask 255.255.255.0"
defaultrouter="10.0.2.2"

# System Daemons & Services
httpd_enable="YES"
sshd_enable="YES"
syslogd_enable="NO"

# Graphical Desktop (X11 + SzpontDesktop)
x11_enable="NO"
