# /etc/rc.subr -- SzpontOS Shell Subroutine Library for RC Scripts
# (C) Copyright by Szpont Industries. Inspired by FreeBSD rc.subr.

checkyesno() {
    eval _value=\$1
    case "$_value" in
        [Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

load_rc_config() {
    if [ -f /etc/rc.conf ]; then
        . /etc/rc.conf
    fi
}
