#!/usr/bin/env python3
"""
Generate panic_image.h from an image file using QOI compression.
(C) Copyright by Szpont Industries. All rights reserved.
"""

import subprocess
import struct
import sys
import os

def main():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    if len(sys.argv) >= 3:
        jpg_path = sys.argv[1]
        header_path = sys.argv[2]
    elif len(sys.argv) == 2:
        jpg_path = sys.argv[1]
        header_path = os.path.join(repo_root, "build", "include", "drivers", "panic_image.h")
    else:
        jpg_path = os.path.join(repo_root, "artwork", "szpont-detected.jpg")
        header_path = os.path.join(repo_root, "build", "include", "drivers", "panic_image.h")

    if not os.path.exists(jpg_path):
        print(f"Error: {jpg_path} not found")
        sys.exit(1)

    os.makedirs(os.path.dirname(os.path.abspath(header_path)), exist_ok=True)
    tmp_bmp = "/tmp/szpont_panic_temp.bmp"

    # Convert JPG to BMP using sips on macOS or convert/magick
    try:
        res = subprocess.run(["sips", "-s", "format", "bmp", jpg_path, "--out", tmp_bmp], capture_output=True)
    except FileNotFoundError:
        res = None
    if res is None or res.returncode != 0:
        res = subprocess.run(["convert", jpg_path, tmp_bmp], capture_output=True)

    with open(tmp_bmp, "rb") as f:
        data = f.read()

    try:
        os.remove(tmp_bmp)
    except:
        pass

    offset = struct.unpack_from("<I", data, 10)[0]
    w, raw_h, bpp = struct.unpack_from("<iiH", data, 18)[0], struct.unpack_from("<iiH", data, 18)[1], struct.unpack_from("<H", data, 28)[0]
    h = abs(raw_h)
    top_down = (raw_h < 0)

    print(f"  [GEN] {header_path} ({w}x{h}, {bpp} bpp)")

    row_stride = ((w * (bpp // 8) + 3) & ~3)
    pixels = []
    bytes_per_pixel = bpp // 8

    for y in range(h):
        if top_down:
            row_offset = offset + y * row_stride
        else:
            row_offset = offset + (h - 1 - y) * row_stride

        for x in range(w):
            px_off = row_offset + x * bytes_per_pixel
            b, g, r = data[px_off], data[px_off+1], data[px_off+2]
            pixels.append((r, g, b, 255))

    # Encode to QOI
    QOI_OP_INDEX  = 0x00
    QOI_OP_DIFF   = 0x40
    QOI_OP_LUMA   = 0x80
    QOI_OP_RUN    = 0xc0
    QOI_OP_RGB    = 0xfe
    QOI_OP_RGBA   = 0xff

    index = [(0, 0, 0, 0)] * 64
    bytes_out = bytearray(b"qoif" + struct.pack(">IIBB", w, h, 3, 0))

    def color_hash(r, g, b, a):
        return (r * 3 + g * 5 + b * 7 + a * 11) % 64

    px_prev = (0, 0, 0, 255)
    run = 0

    for px in pixels:
        if px == px_prev:
            run += 1
            if run == 62:
                bytes_out.append(QOI_OP_RUN | (run - 1))
                run = 0
        else:
            if run > 0:
                bytes_out.append(QOI_OP_RUN | (run - 1))
                run = 0

            index_pos = color_hash(*px)
            if index[index_pos] == px:
                bytes_out.append(QOI_OP_INDEX | index_pos)
            else:
                index[index_pos] = px
                r, g, b, a = px
                pr, pg, pb, pa = px_prev
                vr = r - pr
                vg = g - pg
                vb = b - pb
                vg_r = vr - vg
                vg_b = vb - vg
                if -2 <= vr <= 1 and -2 <= vg <= 1 and -2 <= vb <= 1:
                    bytes_out.append(QOI_OP_DIFF | ((vr + 2) << 4) | ((vg + 2) << 2) | (vb + 2))
                elif -32 <= vg <= 31 and -8 <= vg_r <= 7 and -8 <= vg_b <= 7:
                    bytes_out.append(QOI_OP_LUMA | (vg + 32))
                    bytes_out.append(((vg_r + 8) << 4) | (vg_b + 8))
                else:
                    bytes_out.append(QOI_OP_RGB)
                    bytes_out.extend([r, g, b])
            px_prev = px

    if run > 0:
        bytes_out.append(QOI_OP_RUN | (run - 1))

    bytes_out.extend(b"\x00\x00\x00\x00\x00\x00\x00\x01")

    # Format as C header
    with open(header_path, "w") as f:
        f.write("/*\n")
        f.write(" * SzpontOS - Embedded Kernel Panic Artwork\n")
        f.write(" * Auto-generated by scripts/generate_panic_image.py into build directory.\n")
        f.write(" * (C) Copyright by Szpont Industries. All rights reserved.\n")
        f.write(" */\n\n")
        f.write("#ifndef SZPONTOS_DRIVERS_PANIC_IMAGE_H\n")
        f.write("#define SZPONTOS_DRIVERS_PANIC_IMAGE_H\n\n")
        f.write("#include <stdint.h>\n")
        f.write("#include <stddef.h>\n\n")
        f.write(f"#define PANIC_IMAGE_WIDTH  {w}\n")
        f.write(f"#define PANIC_IMAGE_HEIGHT {h}\n\n")
        f.write("static const uint8_t g_panic_image_qoi[] = {\n")

        for i in range(0, len(bytes_out), 16):
            chunk = bytes_out[i:i+16]
            hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
            if i + 16 < len(bytes_out):
                f.write(f"    {hex_str},\n")
            else:
                f.write(f"    {hex_str}\n")

        f.write("};\n\n")
        f.write("static const size_t g_panic_image_qoi_size = sizeof(g_panic_image_qoi);\n\n")
        f.write("#endif /* SZPONTOS_DRIVERS_PANIC_IMAGE_H */\n")

if __name__ == "__main__":
    main()
