[binaries]
c = '@ROOT_DIR@/scripts/szpontos-gcc'
cpp = '@ROOT_DIR@/scripts/szpontos-g++'
ar = 'x86_64-elf-ar'
ranlib = 'x86_64-elf-ranlib'
strip = 'x86_64-elf-strip'
pkg-config = 'pkg-config'

[properties]
needs_exe_wrapper = true
sys_root = '@SYSROOT_DIR@'
pkg_config_libdir = '@SYSROOT_DIR@/usr/lib/pkgconfig:@SYSROOT_DIR@/usr/share/pkgconfig'
# Cairo's meson.build probes SysV SHM semantics via cc.run(), which cannot
# execute in a cross env. It explicitly supports answering via this property.
# SzpontOS implements Linux-compatible SysV SHM (deferred IPC_RMID release).
ipc_rmid_deferred_release = true

[built-in options]
c_args = ['-O2', '-ffreestanding', '-fno-builtin', '-isystem', '@SYSROOT_DIR@/usr/include', '-B@SYSROOT_DIR@/usr/lib', '-D__szpontos__=1', '-D__linux__=1', '-D__unix__=1', '-D_GNU_SOURCE=1']
c_link_args = ['-L@SYSROOT_DIR@/usr/lib', '-B@SYSROOT_DIR@/usr/lib', '-Wl,-rpath-link,@SYSROOT_DIR@/usr/lib', '-lc', '-lm', '-lz']
cpp_args = ['-O2', '-ffreestanding', '-fno-builtin', '-nostdinc++', '-isystem', '@SYSROOT_DIR@/usr/include/c++', '-isystem', '@SYSROOT_DIR@/usr/include/c++/bits', '-isystem', '@SYSROOT_DIR@/usr/include/c++/backward', '-isystem', '@SYSROOT_DIR@/usr/include/c++/ext', '-isystem', '@SYSROOT_DIR@/usr/include', '-B@SYSROOT_DIR@/usr/lib', '-D__szpontos__=1', '-D__linux__=1', '-D__unix__=1', '-D_GNU_SOURCE=1']
cpp_link_args = ['-L@SYSROOT_DIR@/usr/lib', '-B@SYSROOT_DIR@/usr/lib', '-Wl,-rpath-link,@SYSROOT_DIR@/usr/lib', '-lstdc++', '-lm', '-lc', '-lz']

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
